{
  "name": "durandal/amd/almond-custom",
  "inlineText": true,
  "stubModules": [
    "durandal/amd/text"
  ],
  "paths": {
    "text": "durandal/amd/text"
  },
  "baseUrl": "C:\\Users\\gill\\Documents\\Visual Studio 2012\\Projects\\IARC\\OnLineRadioCourse\\App",
  "mainConfigFile": "C:\\Users\\gill\\Documents\\Visual Studio 2012\\Projects\\IARC\\OnLineRadioCourse\\App\\main.js",
  "include": [
    "main",
    "durandal/app",
    "durandal/composition",
    "durandal/events",
    "durandal/http",
    "text!durandal/messageBox.html",
    "durandal/messageBox",
    "durandal/modalDialog",
    "durandal/system",
    "durandal/viewEngine",
    "durandal/viewLocator",
    "durandal/viewModel",
    "durandal/viewModelBinder",
    "durandal/widget",
    "durandal/plugins/router",
    "durandal/transitions/entrance",
    "durandal/widgets/expander/controller",
    "text!durandal/widgets/expander/view.html",
    "services/cachingService",
    "services/displayService",
    "services/enums",
    "services/themeManager",
    "services/utilities",
    "viewmodels/addlinks",
    "viewmodels/addpresentations",
    "viewmodels/addusers",
    "viewmodels/addvideos",
    "viewmodels/audit",
    "viewmodels/exams",
    "viewmodels/examsmanager",
    "viewmodels/files",
    "viewmodels/filesmanager",
    "viewmodels/forum",
    "viewmodels/home",
    "viewmodels/lessons",
    "viewmodels/lessonsmanager",
    "viewmodels/links",
    "viewmodels/login",
    "viewmodels/presentations",
    "viewmodels/shell",
    "viewmodels/userdetails",
    "viewmodels/videos",
    "viewmodels/_lessons",
    "text!views/addlinks.html",
    "text!views/addpresentations.html",
    "text!views/addusers.html",
    "text!views/addvideos.html",
    "text!views/audit.html",
    "text!views/detail.html",
    "text!views/exams.html",
    "text!views/examsmanager.html",
    "text!views/files.html",
    "text!views/filesmanager.html",
    "text!views/forum.html",
    "text!views/home.html",
    "text!views/lessons.html",
    "text!views/lessonsmanager.html",
    "text!views/links.html",
    "text!views/login.html",
    "text!views/presentations.html",
    "text!views/shell.html",
    "text!views/userdetails.html",
    "text!views/videos.html",
    "text!views/_lessons.html"
  ],
  "exclude": [],
  "keepBuildDir": true,
  "optimize": "uglify2",
  "out": "C:\\Users\\gill\\Documents\\Visual Studio 2012\\Projects\\IARC\\OnLineRadioCourse\\App\\main-built.js",
  "pragmas": {
    "build": true
  },
  "wrap": true,
  "insertRequire": [
    "main"
  ]
}